# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
use_frameworks!

#if latest version is not downloaded, try 'pod repo update' command to reload your cocoapod repo
target 'ShopLiveSwiftSample' do
  pod 'ShopLive' #latest versin 1.5.0
  pod 'ShopliveShortformSDK' #latest versin 1.5.
  pod 'ShopliveSDKCommon' #latest versin 1.5.
end

