# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
use_frameworks!


target 'ShopLiveSwiftSample' do
#  pod 'ShopLive', '1.4.2'
#  pod 'ShopliveShortformSDK', '1.4.0'
end

